name: Lint
on:
  workflow_call:
permissions:
  actions: write
  contents: read
jobs:
  lint:
    runs-on: ${{ fromJSON((github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository) && vars.LOCAL_RUNNER_LABELS || '["ubuntu-latest"]') }}

    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - uses: ./.github/actions/cache-checkout
      - uses: ./.github/actions/yarn-install
      - name: Run Lint
        run: yarn lint
